name: finki-hub-services-scraper

services:
  scraper:
    image: ghcr.io/finki-hub/services-scraper:latest
    restart: unless-stopped
    environment:
      POSTHOG_KEY: ${POSTHOG_KEY:-}
      POSTHOG_HOST: ${POSTHOG_HOST:-https://eu.i.posthog.com}
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
      - ./logs:/app/logs
