name: Docker

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: finki-hub/.github/.github/workflows/docker.yaml@c545734f912fe47b9d24533e495471f4496cdf79
    with:
      build-args: APP_REVISION=${{ github.sha }}
    secrets: inherit
